### ISSUE TITLE
GTNH Nei causing crash when attempting to use with FTB Infinity Evolved

### ISSUE THREAD

**Issue by Forstrei** [GTNewHorizons/NotEnoughItems#121]
This issue was brought up over on the curseforge page, and someone mentioned that it needed to be posted here for any real help. Trying to use this (vastly superior) version of NEI with the FTB Infinity Evolved modpack just causes it to crash repeatedly. I'm not savvy enough to read it, but I've provided the long generated by the crash. Any help would be appreciated.

[2021-05-13-7.log.gz](https://github.com/GTNewHorizons/NotEnoughItems/files/6474729/2021-05-13-7.log.gz)
[latest.log](https://github.com/GTNewHorizons/NotEnoughItems/files/6474730/latest.log)

**Comment by mitchej123** [comment]
I'm seeing a lot of `NotEnoughItems-1.7.10-1.0.5.120-universal.jar` in the logs.  If you've added the gtnh fork of NEI please be sure to remove the stock version otherwise they'll cause clashes, potentially like you're seeing.  

If you still have issues after removing the 1.x series, please make sure you're on the latest release https://github.com/GTNewHorizons/NotEnoughItems/releases/tag/2.1.2-GTNH and report back.

**Comment by Forstrei** [comment]
Thank you, that was it entirely and it was painfully obvious.
