### ISSUE TITLE
Feature Suggestion: Bookmark Locking

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/NotEnoughItems#16]
As many circuit components are used over and over, I tend to have them on my bookmark list, but sometimes forget that I do, and try to bookmark them again, leading to me unbookmarking and rebookmarking them, putting them in the 'wrong' order. I imagine people who have more bookmarks than I do encounter this problem even more.

Therefore I believe it would be nice if you could 'lock' either individual items or rows. Perhaps with a visual indicator, or not. Probably with another keybind. 

Also, drag and drop moving/sorting would be nice if that's not hard.

**Comment by ryankhart** [comment]
For what it's worth, I do like the way it is implemented better than the JEI way for my personal use case. In JEI, bookmarking adds the item to the top left, pushing everything else to the right and wrapping lines, messing up my memory for where things are. I also like being able to unbookmark items from wherever because sometimes I forgot where I bookmarked it in the first place, so in some cases, it's nice to unbookmark and rebookmark again.

Maybe an improvement to fix this could be some sort of drag and drop functionality in the bookmarks pane, but that sounds like it could be complicated since neither NEI, nor JEI have drag and drop anything, only left-click and right-click.

**Comment by slprime** [comment]
![nei-bookmarks-sorting](https://user-images.githubusercontent.com/31038811/140698867-7c88b45c-02c3-4e07-8bf9-14f3b12b4175.gif)
Add Sotring in bookmarks?
