### ISSUE TITLE
'Low' liquid amount render

### ISSUE THREAD

**Issue by Mudresistor** [GTNewHorizons/NotEnoughItems#394]
IDK how to correctly explain, but to look what amount of liquid is required in a recipe for example in II, you need to search below the actual picture. 

![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/53641872/e8c60f55-b5cc-4025-8880-a3ded5db27e5)

**Comment by wlhlm** [comment]
Can you please spell out what 'II' means? If this is a mod or modpack, please list the version of those.

Also, does this work with regular non-GTNH NEI? What I'm trying to ascertain is, whether this is an issue with out NEI, Usually these recipes views are provided by external mods, not NEI itself and the bug might be with the other mod and not NEI.

**Comment by Mudresistor** [comment]
> 

Yeah, sure. It means Immersive Engineering. It's a mod.
And yes, display works correctly with non-GTNH NEI. Also providing you with screenshots of my own mod.
First pic is regular NEI, second -- GTNH.
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/53641872/3d7e4f6f-f4f6-4284-addc-415603161595)
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/53641872/ab8776a1-d0bf-495b-a98d-fa570899af37)

**Comment by wlhlm** [comment]
It's taken me a while, but I've finally implemented a fix for the Immersive Engineering issue in #395.

Regarding the issue in your own mod: this is caused by you assuming a fixed recipe screen layout. However our version of NEI changed this in two ways:
1. the recipe screen now has a flexible length and is no longer centered vertically
2. the recipe paging widget was moved from the bottom of the recipe screen to the top, changing the offset from 16px to 32px

Potential pitfalls are using `GuiScreen.height` to calculate the top of the recipe screen instead of `guiTop`, or using 

You should make your recipe handler more layout-agnostic. In #395 I've also added recommendations for this as well as documentation for adding new features of our NEI version to your own mod. You can read a preview [here](https://github.com/GTNewHorizons/NotEnoughItems/blob/48480504afe88499e90d4deaba1cff00f942defc/README.md#adding-support-for-gtnh-nei-features-to-your-mod). Please let me know if this documentation is in any way confusing or needs to be improved and if you were able to fix the issue on your side.

**Comment by Mudresistor** [comment]
Thank you!
Sorry, i was away for a while. So. To clarify. I installed the last version of NEI and offset really changed from 32 to 16 px, but it is still low. For my mod, undestandable, i will fix ASAP. But for Immersive it looks like this now.
![image](https://github.com/GTNewHorizons/NotEnoughItems/assets/53641872/63c2568c-00eb-45ba-a030-cc7edf7b86d8)

**Comment by wlhlm** [comment]
Ah, I missed checking the Fermenter. Should be fixed now. Please try this build: https://github.com/GTNewHorizons/NotEnoughItems/suites/14137782293/artifacts/791700114

Also, make sure to clear your NEI config.

**Comment by Mudresistor** [comment]
Good! Works now, thank you!
