### ISSUE TITLE
Crash due to text identifiers

### ISSUE THREAD

**Issue by GedeonGrays** [GTNewHorizons/NotEnoughItems#427]
Hello o/

**NEI Version:** 2.4.3-GTNH
**CCC Version:** 1.1.11

**Crash report:** https://pastebin.com/z4R4Fcfv

When trying to add any item to the bookmarks panel using the 'A' hotkey, the client crashes. 
This is due to the "text item IDs instead of numeric for storing in NBT" feature built into ASJCore (by AlexSocol).

**Comment by miozune** [comment]
The mentioned config seems to be doing too invasive modification, no wonder it breaks compatibility with other mods. Please ask the author of ASJCore.

**Comment by AlexSocol** [comment]
@miozune 
> The mentioned config seems to be doing too invasive modification

That is not because of my _invasive modification_, but because you are [saving numerical id to Integer](https://github.com/GTNewHorizons/NotEnoughItems/blob/master/src/main/java/codechicken/nei/recipe/stackinfo/DefaultStackStringifyHandler.java#L38) instead of Short as it is in vanilla. But OK, I'll _fix_ it on my side -_-

**Comment by miozune** [comment]
Oh I see, I can patch it on our end

**Comment by GedeonGrays** [comment]
> Oh I see, I can patch it on our end

I've tested your fix – everything works fine. Thanks for the quick fix.
